[project]
name = "buddy-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography==48.0.0",
    "nuitka==2.7.12",
    "pyinstaller==6.20.0",
    "pyside6==6.8.3",
    "pyside6-addons==6.8.3",
    "pyside6-essentials==6.8.3",
    "pysocks>=1.7.1",
    "requests==2.34.2",
    "charset_normalizer>=3.3.0",
    "urllib3>=2.0.0",
    "certifi>=2024.0.0",
    "idna>=3.4.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
